### ISSUE TITLE
Sequential IDs Not MySQL Compatible?

### ISSUE THREAD

**Issue by danfinlay** [geddy/model#241]
I tried hooking up my app (which uses Sequential IDs) to a MySQL database where I'd used Postgres before, and during `db:init` it threw an error:

```
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'BIGSERIAL PRIMARY KEY, `created_at` TIMESTAMP NULL, `updated_at` TIMESTAMP NULL,' at line 1
    at Query.Sequence._packetToError (/my_project/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/my_project/node_modules/mysql/lib/protocol/sequences/Query.js:82:18)
    at Protocol._parsePacket (/my_project/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/my_project/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/my_project/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/my_project/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
```

I suspect this has to do with a data type that isn't MySQL supported, but I'm not sure yet.

**Comment by AlexRaylight** [comment]
A heads up that 6.0.2, which fixes this problem, is not yet available on npm, which leads to geddy still being broken.
